version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - theworld
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/alertsdb

  postgres:
    image: postgres:13
    hostname: postgres
    networks:
      - theworld
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alertsdb
    volumes:
      - ./migrations:/app/migrations
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres_data:
  migrations:

networks:
  theworld:
    driver: bridge